services:
  # integration that handles mastering machinery completions and corresponding certificates
  # as well as registrations from the moodle course
  fabman-moodle-integration: 
    restart: always
    networks:
      - internal
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fabman-moodle-integration
    environment:
      # customize these if necessary
      - MAIL_USER=r.reyer@hs-mannheim.de
      - DEBUG_MODE=TRUE
      - FABMAN_ACCOUNT_ID=2926
      - GOTENBERG_URL=http://gotenberg:3000
      - NOTIFICATION_MAILADDRESS=r.reyer@hs-mannheim.de
      - MOODLE_USERNAME=reyer
      # REPLACE ${...} with your secrets or create an .env file
      # in this directory containing the following env vars
      - FABMAN_API_KEY=${FABMAN_API_KEY}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}

  gotenberg:
    restart: always
    image: gotenberg/gotenberg:7
    networks:
      - internal

networks:
  internal:
    driver: bridge