services:
  # integration that handles mastering machinery completions and corresponding certificates
  # as well as registrations from the moodle course
  fabman-moodle-integration: 
    restart: always
    networks:
      - internal
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fabman-moodle-integration
    env_file:
      - .env


  # PDF Rendering Engine
  gotenberg:
    restart: always
    image: gotenberg/gotenberg:7
    networks:
      - internal

networks:
  internal:
    driver: bridge